### ISSUE TITLE
ENERGY-SIM?

### ISSUE THREAD

**Issue by MattForshaw** [bda4s/bda4s.github.io#1]
Hi @stevemcgough,

Shall i add links to the Previous workshops page for ENERGY-SIM, per https://github.com/ENERGY-SIM/energy-sim.github.io/edit/master/previous.md, or would you like it keeping completely separate?

Best wishes,
Matt

**Comment by stevemcgough** [comment]
This could be a double-edged sword. We don’t want people to think that we only accept papers like the ENERGY-SIM, but likewise we want to show that we have prior form. Perhaps if we list them as ‘co-related’ past events or something?

Cheers,

Steve..
